### ISSUE TITLE
MySQL incompatible with 'ORDER BY' or 'LIMIT' with multi-table 'UPDATE' queries

### ISSUE THREAD

**Issue by badeed** [MrTwinkles47/Stepmania-Stream-Tools-MrTwinkles#31]
![error mania](https://user-images.githubusercontent.com/34519837/144723662-74878fe8-6cd1-4ae6-a168-7630470e1552.png)

MySQL 5.6.51

**Comment by badeed** [comment]
Reference: [#1221 - Incorrect usage of UPDATE and ORDER BY](https://stackoverflow.com/questions/39384009/1221-incorrect-usage-of-update-and-order-by)

**Comment by MrTwinkles47** [comment]
What version of MariaDB are you running?

**Comment by badeed** [comment]
Ops i an using MySQL 5.6.51 not MariaDB

**Comment by MrTwinkles47** [comment]
Looks like you were able to find one of the few weird differences between MySQL and MariaDB. It seems MySQL (all versions) doesn't support 'ORDER BY' or 'LIMIT' with multi-table 'UPDATE' queries. MariaDB > 10.3-ish does support it.
Are you able to run MariaDB on your setup? 
It is possible for this query to be rewritten to support MySQL+MariaDB.

**Comment by badeed** [comment]
sadly i can't run it on my set up. 
i am just using the database that came with my godaddy webhosting :P. i dont think they offer any other.

I am not quite sure the difference between MariaDB and MySQL. 
but why wouldnt it be possible? worse case scenario you have 2 database query's under a config option "are you running MySQL or MariaDB"

**Comment by MrTwinkles47** [comment]
Long story short, MariaDB is continuation of the open source project after Oracle bought MySQL.
If I rewrite the query to support MySQL, it will work just fine in MariaDB, too. This error just never came up in development since we've all been running MariaDB.

**Comment by badeed** [comment]
i havent faced any other issues beside that one. but i havent made a full on test.

**Comment by badeed** [comment]
@MrTwinkles47 does the code i committed work on MariaDB?

[b741d44](https://github.com/badeed/Stepmania-Stream-Tools-MrTwinkles/commit/b741d44af1a764a672a710df4da96643957760bf)

**Comment by MrTwinkles47** [comment]
Oh, sorry, I didn't see that you already had a fix.
I don't see any immediate errors running the query on my setup; however, that was not done with live data, so I'm not sure if the query still completes the original function or not.

**Comment by badeed** [comment]
it should be the same logically, but idk if MariaDB has different context. 
but still havent tested many use cases
